name: UI Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4.1.1

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.13'

      # Set up PDM with caching
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
          cache: true

      # Install project dependencies and Playwright Chromium
      - name: Install dependencies and Playwright
        run: |
          pdm install --prod --no-self --no-editable
          pdm run playwright install chromium

      # Install Allure CLI with OpenJDK
      - name: Install Allure
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-17-jre
          curl -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.33.0/allure-commandline-2.33.0.tgz | sudo tar -xz -C /opt/
          sudo ln -sf /opt/allure-2.33.0/bin/allure /usr/bin/allure

      # Run UI tests with Playwright and Allure
      - name: Run UI tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: pdm run pytest -sv --alluredir=allure-results
        continue-on-error: true

      # List Allure results
      - name: List Allure results
        run: ls -la allure-results

      # Generate Allure report
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
